# Dockerfile.frontend

# Base image for building
FROM node:20-slim AS builder

WORKDIR /app

# Copy the entire frontend project
COPY . .

RUN npm install
RUN npm run build

# Production image
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000
CMD ["npm", "start"]

