apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yml --out clusters/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  type: NodePort
  ports:
    - name: "80"
      port: 80 # Puerto que expondrá el servicio
      targetPort: 3000 # Puerto donde escucha tu contenedor
      nodePort: 30080 # Puerto del nodo (si usas NodePort)
  selector:
    io.kompose.service: frontend
